version: '3.3'

services:

  keycloak:
    image: jboss/keycloak:3.4.1.Final
    ports:
    - "19191:8080/tcp"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: ukeycloak
      POSTGRES_PASSWORD: password
      POSTGRES_PORT_5432_TCP_ADDR: 192.168.0.23
      POSTGRES_PORT_5432_TCP_PORT: 15432

  pgdb:
    image: postgres:10.1
    hostname: pgdb
    ports:
    - 15432:5432/tcp
    environment:
    - POSTGRES_PASSWORD=password
    volumes:
    - pg-db-ide-volume:/var/lib/postgresql/data

volumes:
  pg-db-ide-volume:
    driver: local

